# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Oficinas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher', '~> 4.10.1'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'

  target 'OficinasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OficinasUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
